=== markpol/5e-database/schema/5e-SRD-Conditions.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "index": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "translatable": true
    },
    "desc": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "translatable": true
    },
    "url": {
      "type": "string"
    },
    "effects": {
      "type": "object",
      "properties": {
        "includes": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "rolls": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "roll": {
                "type": "string",
                "enum": [
                  "attack",
                  "ability_check",
                  "saving_throw",
                  "death_saving_throw"
                ]
              },
              "mode": {
                "type": "string",
                "enum": [
                  "advantage",
                  "disadvantage",
                  "auto_fail"
                ]
              },
              "abilities": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "str",
                    "dex",
                    "con",
                    "int",
                    "wis",
                    "cha"
                  ]
                }
              },
              "attack_kind": {
                "type": "string",
                "enum": [
                  "melee_weapon",
                  "weapon",
                  "bound_weapon"
                ]
              },
              "requires_sense": {
                "type": "string",
                "enum": [
                  "sight",
                  "hearing"
                ]
              },
              "while": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "source_in_line_of_sight",
                    "can_see_attacker",
                    "not_incapacitated",
                    "speed_above_0",
                    "not_wearing_armor",
                    "not_wearing_heavy_armor"
                  ]
                }
              }
            },
            "required": [
              "roll",
              "mode"
            ],
            "additionalProperties": false
          }
        },
        "rolls_against": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "roll": {
                "type": "string",
                "enum": [
                  "attack",
                  "ability_check"
                ]
              },
              "mode": {
                "type": "string",
                "enum": [
                  "advantage",
                  "disadvantage"
                ]
              },
              "critical_hit": {
                "type": "boolean",
                "const": true
              },
              "within_ft": {
                "type": "number"
              },
              "beyond_ft": {
                "type": "number"
              },
              "by": {
                "type": "string",
                "const": "source"
              },
              "purpose": {
                "type": "string",
                "const": "social_interaction"
              },
              "while": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "source_in_line_of_sight",
                    "can_see_attacker",
                    "not_incapacitated",
                    "speed_above_0",
                    "not_wearing_armor",
                    "not_wearing_heavy_armor"
                  ]
                }
              }
            },
            "required": [
              "roll"
            ],
            "additionalProperties": false
          }
        },
        "bonuses": {
          "minItems": 1,
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "to": {
                    "type": "string",
                    "enum": [
                      "attack_roll",
                      "damage_roll",
                      "saving_throw",
                      "armor_class"
                    ]
                  },
                  "attack_kind": {
                    "type": "string",
                    "enum": [
                      "melee_weapon",
                      "weapon",
                      "bound_weapon"
                    ]
                  },
                  "damage_type": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "number"
                  },
                  "uses": {
                    "type": "number"
                  },
                  "dice": {
                    "type": "string"
                  }
                },
                "required": [
                  "to",
                  "dice"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "to": {
                    "type": "string",
                    "enum": [
                      "attack_roll",
                      "damage_roll",
                      "saving_throw",
                      "armor_class"
                    ]
                  },
                  "attack_kind": {
                    "type": "string",
                    "enum": [
                      "melee_weapon",
                      "weapon",
                      "bound_weapon"
                    ]
                  },
                  "damage_type": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "number"
                  },
                  "uses": {
                    "type": "number"
                  },
                  "flat": {
                    "type": "number"
                  }
                },
                "required": [
                  "to",
                  "flat"
                ],
                "additionalProperties": false
              },
              {
                "type": "object",
                "properties": {
                  "to": {
                    "type": "string",
                    "enum": [
                      "attack_roll",
                      "damage_roll",
                      "saving_throw",
                      "armor_class"
                    ]
                  },
                  "attack_kind": {
                    "type": "string",
                    "enum": [
                      "melee_weapon",
                      "weapon",
                      "bound_weapon"
                    ]
                  },
                  "damage_type": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "number"
                  },
                  "uses": {
                    "type": "number"
                  },
                  "ability_modifier": {
                    "type": "string",
                    "enum": [
                      "str",
                      "dex",
                      "con",
                      "int",
                      "wis",
                      "cha"
                    ]
                  }
                },
                "required": [
                  "to",
                  "ability_modifier"
                ],
                "additionalProperties": false
              }
            ]
          }
        },
        "armor_class": {
          "type": "object",
          "properties": {
            "base": {
              "type": "object",
              "properties": {
                "value": {
                  "type": "number"
                },
                "ability_modifier": {
                  "type": "string",
                  "enum": [
                    "str",
                    "dex",
                    "con",
                    "int",
                    "wis",
                    "cha"
                  ]
                }
              },
              "required": [
                "value",
                "ability_modifier"
              ],
              "additionalProperties": false
            },
            "while": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "source_in_line_of_sight",
                  "can_see_attacker",
                  "not_incapacitated",
                  "speed_above_0",
                  "not_wearing_armor",
                  "not_wearing_heavy_armor"
                ]
              }
            }
          },
          "required": [
            "base"
          ],
          "additionalProperties": false
        },
        "speed": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "op": {
                  "type": "string",
                  "const": "set"
                },
                "value": {
                  "type": "number"
                },
                "ignores_bonuses": {
                  "type": "boolean",
                  "const": true
                }
              },
              "required": [
                "op",
                "value"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "op": {
                  "type": "string",
                  "const": "halve"
                }
              },
              "required": [
                "op"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "op": {
                  "type": "string",
                  "const": "crawl_only"
                }
              },
              "required": [
                "op"
              ],
              "additionalProperties": false
            }
          ]
        },
        "cannot": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "take_actions",
              "take_reactions",
              "move",
              "speak",
              "see",
              "hear",
              "perceive_surroundings",
              "cast_spells",
              "concentrate",
              "harm_source",
              "move_closer_to_source"
            ]
          }
        },
        "limits": {
          "type": "object",
          "properties": {
            "attacks_per_turn": {
              "type": "number"
            },
            "one_of_action_or_bonus_action": {
              "type": "boolean",
              "const": true
            }
          },
          "additionalProperties": false
        },
        "damage": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "relation": {
                "type": "string",
                "enum": [
                  "resistance",
                  "immunity",
                  "vulnerability"
                ]
              },
              "types": {
                "minItems": 1,
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "while": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "source_in_line_of_sight",
                    "can_see_attacker",
                    "not_incapacitated",
                    "speed_above_0",
                    "not_wearing_armor",
                    "not_wearing_heavy_armor"
                  ]
                }
              }
            },
            "required": [
              "relation",
              "types"
            ],
            "additionalProperties": false
          }
        },
        "immune_to": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "hit_point_maximum": {
          "type": "object",
          "properties": {
            "op": {
              "type": "string",
              "enum": [
                "halve",
                "reduce"
              ]
            }
          },
          "required": [
            "op"
          ],
          "additionalProperties": false
        },
        "ability_scores": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ability": {
                "type": "string",
                "enum": [
                  "str",
                  "dex",
                  "con",
                  "int",
                  "wis",
                  "cha"
                ]
              },
              "op": {
                "type": "string",
                "const": "reduce"
              }
            },
            "required": [
              "ability",
              "op"
            ],
            "additionalProperties": false
          }
        },
        "healing": {
          "type": "string",
          "const": "maximum"
        },
        "drops_held_items": {
          "type": "boolean",
          "const": true
        },
        "provokes_opportunity_attacks": {
          "type": "boolean"
        },
        "death": {
          "type": "boolean",
          "const": true
        },
        "reason": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "removes": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "adds": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "on_remove": {
      "type": "object",
      "properties": {
        "removes": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exhaustion_levels": {
          "type": "number"
        }
      },
      "additionalProperties": false
    },
    "immune_if_feature": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "feature": {
            "type": "string"
          },
          "while_condition": {
            "type": "string"
          }
        },
        "required": [
          "feature"
        ],
        "additionalProperties": false
      }
    },
    "exhaustion_level": {
      "type": "object",
      "properties": {
        "level": {
          "type": "number"
        },
        "next": {
          "type": "string"
        },
        "prev": {
          "type": "string"
        }
      },
      "required": [
        "level"
      ],
      "additionalProperties": false
    },
    "related": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "collection": {
            "type": "string",
            "enum": [
              "rule-sections"
            ]
          },
          "index": {
            "type": "string"
          }
        },
        "required": [
          "collection",
          "index"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "index",
    "name",
    "desc",
    "url",
    "effects"
  ],
  "additionalProperties": false
}

=== markpol/5e-database/src/2014/en/5e-SRD-Conditions.json
[
  {
    "index": "blinded",
    "name": "Blinded",
    "desc": [
      "- A blinded creature can't see and automatically fails any ability check that requires sight.",
      "- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage."
    ],
    "url": "/api/2014/conditions/blinded",
    "effects": {
      "cannot": ["see"],
      "rolls": [
        {
          "roll": "ability_check",
          "mode": "auto_fail",
          "requires_sense": "sight"
        },
        {
          "roll": "attack",
          "mode": "disadvantage"
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage"
        }
      ]
    }
  },
  {
    "index": "charmed",
    "name": "Charmed",
    "desc": [
      "- A charmed creature can't attack the charmer or target the charmer with harmful abilities or magical effects.",
      "- The charmer has advantage on any ability check to interact socially with the creature."
    ],
    "url": "/api/2014/conditions/charmed",
    "effects": {
      "cannot": ["harm_source"],
      "rolls_against": [
        {
          "roll": "ability_check",
          "mode": "advantage",
          "by": "source",
          "purpose": "social_interaction"
        }
      ]
    },
    "immune_if_feature": [
      {
        "feature": "mindless-rage",
        "while_condition": "enraged"
      }
    ]
  },
  {
    "index": "deafened",
    "name": "Deafened",
    "desc": [
      "- A deafened creature can't hear and automatically fails any ability check that requires hearing."
    ],
    "url": "/api/2014/conditions/deafened",
    "effects": {
      "cannot": ["hear"],
      "rolls": [
        {
          "roll": "ability_check",
          "mode": "auto_fail",
          "requires_sense": "hearing"
        }
      ]
    }
  },
  {
    "index": "frightened",
    "name": "Frightened",
    "desc": [
      "- A frightened creature has disadvantage on ability checks and attack rolls while the source of its fear is within line of sight.",
      "- The creature can't willingly move closer to the source of its fear."
    ],
    "url": "/api/2014/conditions/frightened",
    "effects": {
      "cannot": ["move_closer_to_source"],
      "rolls": [
        {
          "roll": "ability_check",
          "mode": "disadvantage",
          "while": ["source_in_line_of_sight"]
        },
        {
          "roll": "attack",
          "mode": "disadvantage",
          "while": ["source_in_line_of_sight"]
        }
      ]
    },
    "immune_if_feature": [
      {
        "feature": "mindless-rage",
        "while_condition": "enraged"
      }
    ]
  },
  {
    "index": "grappled",
    "name": "Grappled",
    "desc": [
      "- A grappled creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
      "- The condition ends if the grappler is incapacitated (see the condition).",
      "- The condition also ends if an effect removes the grappled creature from the reach of the grappler or grappling effect, such as when a creature is hurled away by the thunderwave spell."
    ],
    "url": "/api/2014/conditions/grappled",
    "effects": {
      "speed": {
        "op": "set",
        "value": 0,
        "ignores_bonuses": true
      }
    }
  },
  {
    "index": "incapacitated",
    "name": "Incapacitated",
    "desc": ["- An incapacitated creature can't take actions or reactions."],
    "url": "/api/2014/conditions/incapacitated",
    "effects": {
      "cannot": ["take_actions", "take_reactions"]
    },
    "removes": ["concentrating"]
  },
  {
    "index": "invisible",
    "name": "Invisible",
    "desc": [
      "- An invisible creature is impossible to see without the aid of magic or a special sense. For the purpose of hiding, the creature is heavily obscured. The creature's location can be detected by any noise it makes or any tracks it leaves.",
      "- Attack rolls against the creature have disadvantage, and the creature's attack rolls have advantage."
    ],
    "url": "/api/2014/conditions/invisible",
    "effects": {
      "rolls": [
        {
          "roll": "attack",
          "mode": "advantage"
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "disadvantage"
        }
      ]
    }
  },
  {
    "index": "paralyzed",
    "name": "Paralyzed",
    "desc": [
      "- A paralyzed creature is incapacitated (see the condition) and can't move or speak.",
      "- The creature automatically fails Strength and Dexterity saving throws.",
      "- Attack rolls against the creature have advantage.",
      "- Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature."
    ],
    "url": "/api/2014/conditions/paralyzed",
    "effects": {
      "includes": ["incapacitated"],
      "cannot": ["move", "speak"],
      "rolls": [
        {
          "roll": "saving_throw",
          "mode": "auto_fail",
          "abilities": ["str", "dex"]
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage"
        },
        {
          "roll": "attack",
          "critical_hit": true,
          "within_ft": 5
        }
      ]
    }
  },
  {
    "index": "petrified",
    "name": "Petrified",
    "desc": [
      "- A petrified creature is transformed, along with any nonmagical object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.",
      "- The creature is incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.",
      "- Attack rolls against the creature have advantage.",
      "- The creature automatically fails Strength and Dexterity saving throws.",
      "- The creature has resistance to all damage.",
      "- The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized."
    ],
    "url": "/api/2014/conditions/petrified",
    "effects": {
      "includes": ["incapacitated"],
      "cannot": ["move", "speak", "perceive_surroundings"],
      "rolls": [
        {
          "roll": "saving_throw",
          "mode": "auto_fail",
          "abilities": ["str", "dex"]
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage"
        }
      ],
      "damage": [
        {
          "relation": "resistance",
          "types": ["all"]
        },
        {
          "relation": "immunity",
          "types": ["poison"]
        }
      ],
      "immune_to": ["poisoned", "disease"]
    }
  },
  {
    "index": "poisoned",
    "name": "Poisoned",
    "desc": ["- A poisoned creature has disadvantage on attack rolls and ability checks."],
    "url": "/api/2014/conditions/poisoned",
    "effects": {
      "rolls": [
        {
          "roll": "attack",
          "mode": "disadvantage"
        },
        {
          "roll": "ability_check",
          "mode": "disadvantage"
        }
      ]
    },
    "immune_if_feature": [
      {
        "feature": "purity-of-body"
      },
      {
        "feature": "natures-ward"
      }
    ]
  },
  {
    "index": "prone",
    "name": "Prone",
    "desc": [
      "- A prone creature's only movement option is to crawl, unless it stands up and thereby ends the condition.",
      "- The creature has disadvantage on attack rolls.",
      "- An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage."
    ],
    "url": "/api/2014/conditions/prone",
    "effects": {
      "speed": {
        "op": "crawl_only"
      },
      "rolls": [
        {
          "roll": "attack",
          "mode": "disadvantage"
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage",
          "within_ft": 5
        },
        {
          "roll": "attack",
          "mode": "disadvantage",
          "beyond_ft": 5
        }
      ]
    }
  },
  {
    "index": "restrained",
    "name": "Restrained",
    "desc": [
      "- A restrained creature's speed becomes 0, and it can't benefit from any bonus to its speed.",
      "- Attack rolls against the creature have advantage, and the creature's attack rolls have disadvantage.",
      "- The creature has disadvantage on Dexterity saving throws."
    ],
    "url": "/api/2014/conditions/restrained",
    "effects": {
      "speed": {
        "op": "set",
        "value": 0,
        "ignores_bonuses": true
      },
      "rolls": [
        {
          "roll": "attack",
          "mode": "disadvantage"
        },
        {
          "roll": "saving_throw",
          "mode": "disadvantage",
          "abilities": ["dex"]
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage"
        }
      ]
    }
  },
  {
    "index": "stunned",
    "name": "Stunned",
    "desc": [
      "- A stunned creature is incapacitated (see the condition), can't move, and can speak only falteringly.",
      "- The creature automatically fails Strength and Dexterity saving throws.",
      "- Attack rolls against the creature have advantage."
    ],
    "url": "/api/2014/conditions/stunned",
    "effects": {
      "includes": ["incapacitated"],
      "cannot": ["move"],
      "rolls": [
        {
          "roll": "saving_throw",
          "mode": "auto_fail",
          "abilities": ["str", "dex"]
        }
      ],
      "rolls_against": [
        {
          "roll": "attack",
          "mode": "advantage"
        }
      ]
    }
  },
  {
    "index": "unconscious",
    "name": "Unconscious",
    "desc": [
      "- An unconscious creature is incapacitated (see the condition), can't move or speak, and is unaware of its surroundings.",
      "- The creature drops whatever it's holding and falls prone.",
