=== markpol/5e-database/schema/5e-SRD-Proficiencies.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "index": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "classes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "index": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "note": {
            "type": "string"
          }
        },
        "required": [
          "index",
          "name",
          "url"
        ],
        "additionalProperties": false
      }
    },
    "races": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "index": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "note": {
            "type": "string"
          }
        },
        "required": [
          "index",
          "name",
          "url"
        ],
        "additionalProperties": false
      }
    },
    "reference": {
      "type": "object",
      "properties": {
        "index": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      },
      "required": [
        "index",
        "name",
        "url"
      ],
      "additionalProperties": false
    },
    "url": {
      "type": "string"
    }
  },
  "required": [
    "index",
    "name",
    "type",
    "reference",
    "url"
  ],
  "additionalProperties": false
}

=== markpol/5e-database/src/2014/en/5e-SRD-Proficiencies.json
[
  {
    "index": "light-armor",
    "type": "Armor",
    "name": "Light Armor",
    "classes": [
      {
        "index": "barbarian",
        "name": "Barbarian",
        "url": "/api/2014/classes/barbarian"
      },
      {
        "index": "bard",
        "name": "Bard",
        "url": "/api/2014/classes/bard"
      },
      {
        "index": "cleric",
        "name": "Cleric",
        "url": "/api/2014/classes/cleric"
      },
      {
        "index": "druid",
        "name": "Druid",
        "url": "/api/2014/classes/druid"
      },
      {
        "index": "ranger",
        "name": "Ranger",
        "url": "/api/2014/classes/ranger"
      },
      {
        "index": "rogue",
        "name": "Rogue",
        "url": "/api/2014/classes/rogue"
      },
      {
        "index": "warlock",
        "name": "Warlock",
        "url": "/api/2014/classes/warlock"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/light-armor",
    "reference": {
      "index": "light-armor",
      "name": "Light Armor",
      "url": "/api/2014/equipment-categories/light-armor"
    }
  },
  {
    "index": "medium-armor",
    "type": "Armor",
    "name": "Medium Armor",
    "classes": [
      {
        "index": "barbarian",
        "name": "Barbarian",
        "url": "/api/2014/classes/barbarian"
      },
      {
        "index": "cleric",
        "name": "Cleric",
        "url": "/api/2014/classes/cleric"
      },
      {
        "index": "druid",
        "name": "Druid",
        "url": "/api/2014/classes/druid"
      },
      {
        "index": "ranger",
        "name": "Ranger",
        "url": "/api/2014/classes/ranger"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/medium-armor",
    "reference": {
      "index": "medium-armor",
      "name": "Medium Armor",
      "url": "/api/2014/equipment-categories/medium-armor"
    }
  },
  {
    "index": "heavy-armor",
    "type": "Armor",
    "name": "Heavy Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/heavy-armor",
    "reference": {
      "index": "heavy-armor",
      "name": "Heavy Armor",
      "url": "/api/2014/equipment-categories/heavy-armor"
    }
  },
  {
    "index": "all-armor",
    "type": "Armor",
    "name": "All armor",
    "classes": [
      {
        "index": "fighter",
        "name": "Fighter",
        "url": "/api/2014/classes/fighter"
      },
      {
        "index": "paladin",
        "name": "Paladin",
        "url": "/api/2014/classes/paladin"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/all-armor",
    "reference": {
      "index": "armor",
      "name": "Armor",
      "url": "/api/2014/equipment-categories/armor"
    }
  },
  {
    "index": "padded-armor",
    "type": "Armor",
    "name": "Padded Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/padded-armor",
    "reference": {
      "index": "padded-armor",
      "name": "Padded Armor",
      "url": "/api/equipment/padded-armor"
    }
  },
  {
    "index": "leather-armor",
    "type": "Armor",
    "name": "Leather Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/leather-armor",
    "reference": {
      "index": "leather-armor",
      "name": "Leather Armor",
      "url": "/api/equipment/leather-armor"
    }
  },
  {
    "index": "studded-leather-armor",
    "type": "Armor",
    "name": "Studded Leather Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/studded-leather-armor",
    "reference": {
      "index": "studded-leather-armor",
      "name": "Studded Leather Armor",
      "url": "/api/equipment/studded-leather-armor"
    }
  },
  {
    "index": "hide-armor",
    "type": "Armor",
    "name": "Hide Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/hide-armor",
    "reference": {
      "index": "hide-armor",
      "name": "Hide Armor",
      "url": "/api/equipment/hide-armor"
    }
  },
  {
    "index": "chain-shirt",
    "type": "Armor",
    "name": "Chain Shirt",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/chain-shirt",
    "reference": {
      "index": "chain-shirt",
      "name": "Chain Shirt",
      "url": "/api/equipment/chain-shirt"
    }
  },
  {
    "index": "scale-mail",
    "type": "Armor",
    "name": "Scale Mail",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/scale-mail",
    "reference": {
      "index": "scale-mail",
      "name": "Scale Mail",
      "url": "/api/equipment/scale-mail"
    }
  },
  {
    "index": "breastplate",
    "type": "Armor",
    "name": "Breastplate",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/breastplate",
    "reference": {
      "index": "breastplate",
      "name": "Breastplate",
      "url": "/api/equipment/breastplate"
    }
  },
  {
    "index": "half-plate-armor",
    "type": "Armor",
    "name": "Half Plate Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/half-plate-armor",
    "reference": {
      "index": "half-plate-armor",
      "name": "Half Plate Armor",
      "url": "/api/equipment/half-plate-armor"
    }
  },
  {
    "index": "ring-mail",
    "type": "Armor",
    "name": "Ring Mail",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/ring-mail",
    "reference": {
      "index": "ring-mail",
      "name": "Ring Mail",
      "url": "/api/equipment/ring-mail"
    }
  },
  {
    "index": "chain-mail",
    "type": "Armor",
    "name": "Chain Mail",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/chain-mail",
    "reference": {
      "index": "chain-mail",
      "name": "Chain Mail",
      "url": "/api/equipment/chain-mail"
    }
  },
  {
    "index": "splint-armor",
    "type": "Armor",
    "name": "Splint Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/splint-armor",
    "reference": {
      "index": "splint-armor",
      "name": "Splint Armor",
      "url": "/api/equipment/splint-armor"
    }
  },
  {
    "index": "plate-armor",
    "type": "Armor",
    "name": "Plate Armor",
    "classes": [],
    "races": [],
    "url": "/api/2014/proficiencies/plate-armor",
    "reference": {
      "index": "plate-armor",
      "name": "Plate Armor",
      "url": "/api/equipment/plate-armor"
    }
  },
  {
    "index": "shields",
    "type": "Armor",
    "name": "Shields",
    "classes": [
      {
        "index": "barbarian",
        "name": "Barbarian",
        "url": "/api/2014/classes/barbarian"
      },
      {
        "index": "cleric",
        "name": "Cleric",
        "url": "/api/2014/classes/cleric"
      },
      {
        "index": "druid",
        "name": "Druid",
        "url": "/api/2014/classes/druid"
      },
      {
        "index": "fighter",
        "name": "Fighter",
        "url": "/api/2014/classes/fighter"
      },
      {
        "index": "paladin",
        "name": "Paladin",
        "url": "/api/2014/classes/paladin"
      },
      {
        "index": "ranger",
        "name": "Ranger",
        "url": "/api/2014/classes/ranger"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/shields",
    "reference": {
      "index": "shield",
      "name": "Shield",
      "url": "/api/equipment/shield"
    }
  },
  {
    "index": "simple-weapons",
    "type": "Weapons",
    "name": "Simple Weapons",
    "classes": [
      {
        "index": "barbarian",
        "name": "Barbarian",
        "url": "/api/2014/classes/barbarian"
      },
      {
        "index": "bard",
        "name": "Bard",
        "url": "/api/2014/classes/bard"
      },
      {
        "index": "cleric",
        "name": "Cleric",
        "url": "/api/2014/classes/cleric"
      },
      {
        "index": "fighter",
        "name": "Fighter",
        "url": "/api/2014/classes/fighter"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/classes/monk"
      },
      {
        "index": "paladin",
        "name": "Paladin",
        "url": "/api/2014/classes/paladin"
      },
      {
        "index": "ranger",
        "name": "Ranger",
        "url": "/api/2014/classes/ranger"
      },
      {
        "index": "rogue",
        "name": "Rogue",
        "url": "/api/2014/classes/rogue"
      },
      {
        "index": "warlock",
        "name": "Warlock",
        "url": "/api/2014/classes/warlock"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/simple-weapons",
    "reference": {
      "index": "simple-weapons",
      "name": "Simple Weapons",
      "url": "/api/2014/equipment-categories/simple-weapons"
    }
  },
  {
    "index": "martial-weapons",
    "type": "Weapons",
    "name": "Martial Weapons",
    "classes": [
      {
        "index": "barbarian",
        "name": "Barbarian",
        "url": "/api/2014/classes/barbarian"
      },
      {
        "index": "fighter",
        "name": "Fighter",
        "url": "/api/2014/classes/fighter"
      },
      {
        "index": "paladin",
        "name": "Paladin",
        "url": "/api/2014/classes/paladin"
      },
      {
        "index": "ranger",
        "name": "Ranger",
        "url": "/api/2014/classes/ranger"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/martial-weapons",
    "reference": {
      "index": "martial-weapons",
      "name": "Martial Weapons",
      "url": "/api/2014/equipment-categories/martial-weapons"
    }
  },
  {
    "index": "clubs",
    "type": "Weapons",
    "name": "Clubs",
    "classes": [
      {
        "index": "druid",
        "name": "Druid",
        "url": "/api/2014/classes/druid"
      }
    ],
    "races": [],
    "url": "/api/2014/proficiencies/clubs",
    "reference": {
      "index": "club",
      "name": "Club",
      "url": "/api/equipment/club"
    }
  },
  {
    "index": "daggers",
    "type": "Weapons",
    "name": "Daggers",
    "classes": [
      {
        "index": "druid",
        "name": "Druid",
