=== markpol/5e-database/schema/5e-SRD-Equipment.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "index": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "translatable": true
    },
    "equipment_category": {
      "type": "object",
      "properties": {
        "index": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      },
      "required": [
        "index",
        "name",
        "url"
      ],
      "additionalProperties": false
    },
    "cost": {
      "type": "object",
      "properties": {
        "quantity": {
          "type": "number"
        },
        "unit": {
          "type": "string"
        }
      },
      "required": [
        "quantity",
        "unit"
      ],
      "additionalProperties": false
    },
    "url": {
      "type": "string"
    },
    "desc": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "translatable": true
    },
    "material": {
      "type": "string"
    },
    "stackable": {
      "type": "boolean"
    },
    "ammunition": {
      "type": "string"
    },
    "is_consumable": {
      "type": "boolean"
    },
    "effect": {
      "type": "object",
      "properties": {
        "damage": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "damage_type": {
                "type": "string"
              },
              "damage_dice": {
                "type": "string"
              }
            },
            "required": [
              "damage_type",
              "damage_dice"
            ],
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "weight": {
      "type": "number"
    },
    "gear_category": {
      "type": "object",
      "properties": {
        "index": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "note": {
          "type": "string"
        }
      },
      "required": [
        "index",
        "name",
        "url"
      ],
      "additionalProperties": false
    },
    "armor_category": {
      "type": "string",
      "translatable": true
    },
    "armor_class": {
      "type": "object",
      "properties": {
        "base": {
          "type": "number"
        },
        "dex_bonus": {
          "type": "boolean"
        },
        "max_bonus": {
          "type": "number"
        }
      },
      "required": [
        "base",
        "dex_bonus"
      ],
      "additionalProperties": false
    },
    "capacity": {
      "type": "string",
      "translatable": true
    },
    "category_range": {
      "type": "string",
      "translatable": true
    },
    "contents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "item": {
            "type": "object",
            "properties": {
              "index": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "url": {
                "type": "string"
              },
              "note": {
                "type": "string"
              }
            },
            "required": [
              "index",
              "name",
              "url"
            ],
            "additionalProperties": false
          },
          "quantity": {
            "type": "number"
          }
        },
        "required": [
          "item",
          "quantity"
        ],
        "additionalProperties": false
      }
    },
    "damage": {
      "type": "object",
      "properties": {
        "damage_type": {
          "type": "object",
          "properties": {
            "index": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "index",
            "name",
            "url"
          ],
          "additionalProperties": false
        },
        "damage_dice": {
          "type": "string"
        },
        "dc": {
          "type": "object",
          "properties": {
            "dc_type": {
              "type": "object",
              "properties": {
                "index": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "note": {
                  "type": "string"
                }
              },
              "required": [
                "index",
                "name",
                "url"
              ],
              "additionalProperties": false
            },
            "dc_value": {
              "type": "number"
            },
            "success_type": {
              "type": "string",
              "enum": [
                "none",
                "half",
                "other"
              ]
            }
          },
          "required": [
            "dc_type",
            "success_type"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "damage_type",
        "damage_dice"
      ],
      "additionalProperties": false
    },
    "image": {
      "type": "string"
    },
    "properties": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "index": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "note": {
            "type": "string"
          }
        },
        "required": [
          "index",
          "name",
          "url"
        ],
        "additionalProperties": false
      }
    },
    "quantity": {
      "type": "number"
    },
    "range": {
      "type": "object",
      "properties": {
        "normal": {
          "type": "number"
        },
        "long": {
          "type": "number"
        }
      },
      "required": [
        "normal"
      ],
      "additionalProperties": false
    },
    "special": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "translatable": true
    },
    "speed": {
      "type": "object",
      "properties": {
        "quantity": {
          "type": "number"
        },
        "unit": {
          "type": "string"
        }
      },
      "required": [
        "quantity",
        "unit"
      ],
      "additionalProperties": false
    },
    "stealth_disadvantage": {
      "type": "boolean"
    },
    "str_minimum": {
      "type": "number"
    },
    "throw_range": {
      "type": "object",
      "properties": {
        "normal": {
          "type": "number"
        },
        "long": {
          "type": "number"
        }
      },
      "required": [
        "normal",
        "long"
      ],
      "additionalProperties": false
    },
    "tool_category": {
      "type": "string",
      "translatable": true
    },
    "two_handed_damage": {
      "type": "object",
      "properties": {
        "damage_type": {
          "type": "object",
          "properties": {
            "index": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "url": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          },
          "required": [
            "index",
            "name",
            "url"
          ],
          "additionalProperties": false
        },
        "damage_dice": {
          "type": "string"
        },
        "dc": {
          "type": "object",
          "properties": {
            "dc_type": {
              "type": "object",
              "properties": {
                "index": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "note": {
                  "type": "string"
                }
              },
              "required": [
                "index",
                "name",
                "url"
              ],
              "additionalProperties": false
            },
            "dc_value": {
              "type": "number"
            },
            "success_type": {
              "type": "string",
              "enum": [
                "none",
                "half",
                "other"
              ]
            }
          },
          "required": [
            "dc_type",
            "success_type"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "damage_type",
        "damage_dice"
      ],
      "additionalProperties": false
    },
    "vehicle_category": {
      "type": "string",
      "translatable": true
    },
    "weapon_category": {
      "type": "string",
      "translatable": true
    },
    "weapon_range": {
      "type": "string",
      "translatable": true
    }
  },
  "required": [
    "index",
    "name",
    "equipment_category",
    "cost",
    "url"
  ],
  "additionalProperties": false
}

=== markpol/5e-database/src/2014/en/5e-SRD-Equipment.json
[
  {
    "index": "club",
    "name": "Club",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 1,
      "unit": "sp"
    },
    "damage": {
      "damage_dice": "1d4",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 2,
    "properties": [
      {
        "index": "light",
        "name": "Light",
        "url": "/api/2014/weapon-properties/light"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "material": "wood",
    "url": "/api/2014/equipment/club"
  },
  {
    "index": "dagger",
    "name": "Dagger",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 2,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d4",
      "damage_type": {
        "index": "piercing",
        "name": "Piercing",
        "url": "/api/2014/damage-types/piercing"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 1,
    "properties": [
      {
        "index": "finesse",
        "name": "Finesse",
        "url": "/api/2014/weapon-properties/finesse"
      },
      {
        "index": "light",
        "name": "Light",
        "url": "/api/2014/weapon-properties/light"
      },
      {
        "index": "thrown",
        "name": "Thrown",
        "url": "/api/2014/weapon-properties/thrown"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "throw_range": {
      "normal": 20,
      "long": 60
    },
    "material": "metal",
    "url": "/api/2014/equipment/dagger"
  },
  {
    "index": "greatclub",
    "name": "Greatclub",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 2,
      "unit": "sp"
    },
    "damage": {
      "damage_dice": "1d8",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 10,
    "properties": [
      {
        "index": "two-handed",
        "name": "Two-Handed",
        "url": "/api/2014/weapon-properties/two-handed"
      }
    ],
    "material": "wood",
    "url": "/api/2014/equipment/greatclub"
  },
  {
    "index": "handaxe",
    "name": "Handaxe",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 5,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d6",
      "damage_type": {
        "index": "slashing",
        "name": "Slashing",
        "url": "/api/2014/damage-types/slashing"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 2,
    "properties": [
      {
        "index": "light",
        "name": "Light",
        "url": "/api/2014/weapon-properties/light"
      },
      {
        "index": "thrown",
        "name": "Thrown",
        "url": "/api/2014/weapon-properties/thrown"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "throw_range": {
      "normal": 20,
      "long": 60
    },
    "material": "metal",
    "url": "/api/2014/equipment/handaxe"
  },
  {
    "index": "javelin",
    "name": "Javelin",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 5,
      "unit": "sp"
    },
    "damage": {
      "damage_dice": "1d6",
      "damage_type": {
        "index": "piercing",
        "name": "Piercing",
        "url": "/api/2014/damage-types/piercing"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 2,
    "properties": [
      {
        "index": "thrown",
        "name": "Thrown",
        "url": "/api/2014/weapon-properties/thrown"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "throw_range": {
      "normal": 30,
      "long": 120
    },
    "material": "metal",
    "stackable": true,
    "url": "/api/2014/equipment/javelin"
  },
  {
    "index": "light-hammer",
    "name": "Light hammer",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 2,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d4",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 2,
    "properties": [
      {
        "index": "light",
        "name": "Light",
        "url": "/api/2014/weapon-properties/light"
      },
      {
        "index": "thrown",
        "name": "Thrown",
        "url": "/api/2014/weapon-properties/thrown"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "throw_range": {
      "normal": 20,
      "long": 60
    },
    "material": "metal",
    "url": "/api/2014/equipment/light-hammer"
  },
  {
    "index": "mace",
    "name": "Mace",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 5,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d6",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 4,
    "properties": [
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "material": "metal",
    "url": "/api/2014/equipment/mace"
  },
  {
    "index": "quarterstaff",
    "name": "Quarterstaff",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 2,
      "unit": "sp"
    },
    "damage": {
      "damage_dice": "1d6",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 4,
    "properties": [
      {
        "index": "versatile",
        "name": "Versatile",
        "url": "/api/2014/weapon-properties/versatile"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "two_handed_damage": {
      "damage_dice": "1d8",
      "damage_type": {
        "index": "bludgeoning",
        "name": "Bludgeoning",
        "url": "/api/2014/damage-types/bludgeoning"
      }
    },
    "material": "wood",
    "url": "/api/2014/equipment/quarterstaff"
  },
  {
    "index": "sickle",
    "name": "Sickle",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 1,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d4",
      "damage_type": {
        "index": "slashing",
        "name": "Slashing",
        "url": "/api/2014/damage-types/slashing"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 2,
    "properties": [
      {
        "index": "light",
        "name": "Light",
        "url": "/api/2014/weapon-properties/light"
      },
      {
        "index": "monk",
        "name": "Monk",
        "url": "/api/2014/weapon-properties/monk"
      }
    ],
    "material": "metal",
    "url": "/api/2014/equipment/sickle"
  },
  {
    "index": "spear",
    "name": "Spear",
    "equipment_category": {
      "index": "weapon",
      "name": "Weapon",
      "url": "/api/2014/equipment-categories/weapon"
    },
    "weapon_category": "Simple",
    "weapon_range": "Melee",
    "category_range": "Simple Melee",
    "cost": {
      "quantity": 1,
      "unit": "gp"
    },
    "damage": {
      "damage_dice": "1d6",
      "damage_type": {
        "index": "piercing",
        "name": "Piercing",
        "url": "/api/2014/damage-types/piercing"
      }
    },
    "range": {
      "normal": 5
    },
    "weight": 3,
    "properties": [
      {
        "index": "thrown",
        "name": "Thrown",
        "url": "/api/2014/weapon-properties/thrown"
      },
      {
        "index": "versatile",
        "name": "Versatile",
